"""Small formula checks for Eq. (twostep) of the manuscript (implementation checks, not proofs).

1. Exact rational arithmetic: for quadratics L(x) = 1/2 (x-c)^T A (x-c) with random rational symmetric A,
   U_b(U_a(theta)) - U_a(U_b(theta)) equals eta^2 (H_b g_a - H_a g_b) exactly (Fraction equality).
2. Remainder bound on quartic-perturbed quadratics L(x) = 1/2 r^T A r + kappa/4 sum r_i^4, r = x - c:
   || diff - eta^2 (H_b g_a - H_a g_b) || <= eta^3/2 (M_b ||g_a||^2 + M_a ||g_b||^2), with
   M = 6 kappa R a valid Lipschitz constant of the Hessian (in operator 2-norm) on the segment, where R bounds
   |r_i| over the segment (|r_i| is convex along a segment, so its maximum is at an endpoint).

Writes paper/generated/formula_check.json and prints a one-line summary. Stdlib only.
"""

import json
import math
import os
import random
from fractions import Fraction

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))


def matvec(A, v):
    return [sum(a * x for a, x in zip(row, v)) for row in A]


def sub(u, v):
    return [a - b for a, b in zip(u, v)]


def axpy(s, u, v):
    return [s * a + b for a, b in zip(u, v)]


def exact_quadratic_case(rng, dim):
    def rq():
        return Fraction(rng.randint(-9, 9), rng.randint(1, 9))
    mats, centers = [], []
    for _ in range(2):
        M = [[rq() for _ in range(dim)] for _ in range(dim)]
        mats.append([[M[i][j] + M[j][i] for j in range(dim)] for i in range(dim)])  # symmetric, not nec. PSD
        centers.append([rq() for _ in range(dim)])
    theta = [rq() for _ in range(dim)]
    eta = Fraction(rng.randint(1, 9), rng.randint(2, 20))
    grad = [lambda x, A=A, c=c: matvec(A, sub(x, c)) for A, c in zip(mats, centers)]

    def U(k, x):
        return axpy(-eta, grad[k](x), x)

    diff = sub(U(1, U(0, theta)), U(0, U(1, theta)))
    ga, gb = grad[0](theta), grad[1](theta)
    pred = [eta * eta * (x - y) for x, y in zip(matvec(mats[1], ga), matvec(mats[0], gb))]
    return diff == pred


def quartic_case(rng, dim, kappa, eta):
    def spd():
        M = [[rng.gauss(0, 1) for _ in range(dim)] for _ in range(dim)]
        return [[sum(M[k][i] * M[k][j] for k in range(dim)) / dim + (1.0 if i == j else 0.0)
                 for j in range(dim)] for i in range(dim)]
    losses = [(spd(), [rng.gauss(0, 1) for _ in range(dim)]) for _ in range(2)]
    theta = [rng.gauss(0, 1) for _ in range(dim)]

    def grad(k, x):
        A, c = losses[k]
        r = sub(x, c)
        return [g + kappa * ri ** 3 for g, ri in zip(matvec(A, r), r)]

    def hess(k, x):
        A, c = losses[k]
        r = sub(x, c)
        return [[A[i][j] + (3 * kappa * r[i] ** 2 if i == j else 0.0) for j in range(dim)] for i in range(dim)]

    def U(k, x):
        return axpy(-eta, grad(k, x), x)

    ga, gb = grad(0, theta), grad(1, theta)
    diff = sub(U(1, U(0, theta)), U(0, U(1, theta)))
    pred = [eta * eta * (x - y) for x, y in zip(matvec(hess(1, theta), ga), matvec(hess(0, theta), gb))]
    resid = math.sqrt(sum((d - p) ** 2 for d, p in zip(diff, pred)))

    def R(k, a, b):  # max |r_i| of loss k over the segment [a, b]
        c = losses[k][1]
        return max(max(abs(x - ci) for x, ci in zip(p, c)) for p in (a, b))

    m_b = 6 * kappa * R(1, theta, axpy(-eta, ga, theta))  # Hessian of L_b on [theta, theta - eta g_a]
    m_a = 6 * kappa * R(0, theta, axpy(-eta, gb, theta))
    na2, nb2 = sum(x * x for x in ga), sum(x * x for x in gb)
    bound = 0.5 * eta ** 3 * (m_b * na2 + m_a * nb2)
    return resid, bound


def main():
    rng = random.Random(20260926)
    exact = [exact_quadratic_case(rng, rng.randint(2, 4)) for _ in range(200)]
    quartic = []
    for _ in range(200):
        dim = rng.randint(2, 4)
        eta = 10 ** rng.uniform(-3, -0.5)
        resid, bound = quartic_case(rng, dim, kappa=rng.uniform(0.1, 1.0), eta=eta)
        quartic.append({"eta": eta, "resid": resid, "bound": bound, "ok": resid <= bound * (1 + 1e-9) + 1e-15})
    out = {"exact_quadratic_cases": len(exact), "exact_quadratic_all_equal": all(exact),
           "quartic_cases": len(quartic), "quartic_bound_holds": sum(q["ok"] for q in quartic),
           "quartic_max_resid_over_bound": max(q["resid"] / q["bound"] for q in quartic if q["bound"] > 0),
           "seed": 20260926, "note": "numerical checks of a standard Taylor estimate; not a proof"}
    os.makedirs(os.path.join(ROOT, "paper", "generated"), exist_ok=True)
    with open(os.path.join(ROOT, "paper", "generated", "formula_check.json"), "w") as f:
        json.dump(out, f, indent=1)
    with open(os.path.join(ROOT, "paper", "generated", "formula_numbers.tex"), "w") as f:
        f.write("% AUTO-GENERATED by paper/scripts/check_two_step_identity.py. Do not edit.\n")
        for k in ("exact_quadratic_cases", "quartic_cases", "quartic_bound_holds"):
            f.write(f"\\expandafter\\def\\csname res@fc.{k}\\endcsname{{{out[k]}}}\n")
        f.write(f"\\expandafter\\def\\csname res@fc.exact_all\\endcsname{{{'all' if out['exact_quadratic_all_equal'] else 'NOT all'}}}\n")
        f.write(f"\\expandafter\\def\\csname res@fc.maxratio\\endcsname{{{out['quartic_max_resid_over_bound']:.3f}}}\n")
    print(json.dumps(out))


if __name__ == "__main__":
    main()
